export const images = {
  wave: require("../images/wave-hand.png"),
  e1: require("../images/1.gif"),
  e2: require("../images/2.gif"),
  e3: require("../images/3.gif"),
  e4: require("../images/4.gif"),
  e5: require("../images/5.gif"),
  e6: require("../images/6.gif"),
  e7: require("../images/7.gif"),
  e8: require("../images/8.gif"),
  e9: require("../images/9.gif"),
  e10: require("../images/10.gif"),
  e11: require("../images/11.gif"),
  e12: require("../images/12.gif"),
  e13: require("../images/13.gif"),
  e14: require("../images/14.gif"),
  e15: require("../images/15.gif"),
  e16: require("../images/16.gif"),
  e17: require("../images/17.gif"),
  e18: require("../images/18.gif"),
  e19: require("../images/19.gif"),
  e20: require("../images/20.gif"),
};
